name: typescript-changeset-release-action
description: A GitHub Action to manage GitHub Action's release using changeset

inputs:
  auto-merge:
    description: |
      A boolean value to indicate whether to auto-merge the pull request or not. Default to `false`
    required: false
  # for changesets/action
  commit:
    description: |
      The commit message. Default to `Version Action`
    required: false
    deprecationMessage: "Use `commit-message` instead"
  commit-message:
    description: |
      The commit message. Default to `Version Action`
    required: false
  title:
    description: The pull request title. Default to `Release Action`
    required: false
    deprecationMessage: "Use `pr-title` instead"
  pr-title:
    description: The pull request title. Default to `Release Action`
    required: false
  setupGitUser:
    description: Sets up the git user for commits as `"github-actions[bot]"`. Default to `true`
    required: false
    deprecationMessage: "Use `setup-git-user` instead"
  setup-git-user:
    description: Sets up the git user for commits as `"github-actions[bot]"`. Default to `true`
    required: false
  createGithubReleases:
    description: "A boolean value to indicate whether to create Github releases after `publish` or not"
    required: false
    deprecationMessage: "Use `create-github-releases` instead"
  create-github-releases:
    description: "A boolean value to indicate whether to create Github releases after `publish` or not"
    required: false
  branch:
    description: Sets the branch in which the action will run. Default to `github.ref_name` if not provided
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 20

    - uses: changesets/action@3de3850952bec538fde60aac71731376e57b9b57 # v1.4.8
      id: changeset
      with:
        publish: node ${{ github.action_path }}/dist/main.js
        commit: ${{ inputs.commit-message && inputs.commit-message || inputs.commit && inputs.commit || 'Version Action' }}
        title: ${{ inputs.pr-title && inputs.pr-title || inputs.title && inputs.title || 'Release Action' }}
        setupGitUser: ${{ inputs.setup-git-user && inputs.setup-git-user || inputs.setupGitUser && inputs.setupGitUser || 'true' }}
        createGithubReleases: ${{ inputs.create-github-releases && inputs.create-github-releases || inputs.createGithubReleases && inputs.createGithubReleases || 'false' }}
        branch: ${{ inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - if: ${{ steps.changeset.outputs.pullRequestNumber != '' && inputs.auto-merge == 'true' }}
      shell: sh
      run: gh pr merge --auto "${{ steps.changeset.outputs.pullRequestNumber}}"
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
