name: release

inputs:
  # for changesets/action
  commit:
    description: |
      The commit message. Default to `Version Action`
    required: false
    default: "Version Action"
  title:
    description: The pull request title. Default to `Release Action`
    required: false
    default: "Release Action"
  setupGitUser:
    description: Sets up the git user for commits as `"github-actions[bot]"`. Default to `true`
    required: false
    default: "true"
  createGithubReleases:
    description: "A boolean value to indicate whether to create Github releases after `publish` or not"
    required: false
    default: "true"
  branch:
    description: Sets the branch in which the action will run. Default to `github.ref_name` if not provided
    required: false

description: Release a new version of the package

runs:
  using: composite
  steps:
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 20

    - shell: sh
      run: |
        npm --prefix ${{ github.action_path }} ci

    - uses: changesets/action@3de3850952bec538fde60aac71731376e57b9b57 # v1.4.8
      with:
        publish: node ${{ github.action_path }}/index.js
        commit: ${{ inputs.commit && inputs.commit || 'Version Action' }}
        title: ${{ inputs.title && inputs.title || 'Release Action' }}
        setupGitUser: ${{ inputs.setupGitUser }}
        createGithubReleases: ${{ inputs.createGithubReleases }}
        branch: ${{ inputs.branch }}
