on:
  push:
    branches:
      - renovate/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.username == 'renovate[bot]'
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}

      - uses: YutaUra/renovate-changeset-action@fbaa2e872e2b4b80206556fef3f93889f0e1b9c2 # v0.0.49
        with:
          message: ${{ github.event.head_commit.message }}
          setup-git-user: "false"